### ISSUE TITLE
Set Channel Topic in Slack

### ISSUE THREAD

**Issue by phillfarrugia** [jamescmartinez/coffee#11]
Is deeper Slack integration something that others would want?

I think it would be great if given an upcoming event, the corresponding Slack channel's topic could be updated to provide the date/venue info.

E.g. `Next up: Thursday December 21, 2017, 7pm. Eclipse Bar @ Hyatt Regency`

I'm going to use this as an opportunity to get up to speed on this app, and Rails in general (I don't have much experience). But curious if it's something others see as useful?

**Comment by rodericj** [comment]
I think this is a small enough project that you could do the slack integration without even affecting the current direction that James has in mind. As in there isn’t a huge amount of legacy infra. I’m not sure if this is a time to bring up micro services(?) but I say go for it.

**Comment by jamescmartinez** [comment]
This would be a biggie. You'd have to handle:

1) Slack authentication/authorization
2) Channel selection and association with a group
3) Updating that channel's topic -- the easiest of the three

If you're up for it, though, please do!

**Comment by brennanMKE** [comment]
I once created a tiny Slack bot in TypeScript. I was able to use my personal access token to post messages.

https://gist.github.com/brennanMKE/1f7bee9a2863c7a2433e

Something like it could be used to schedule a message to be posted to the appropriate channel. Another API call may change the channel topic just as easily.

**Comment by jamescmartinez** [comment]
The difficult part that I alluded to above would be creating and storing non-personal access tokens. e.g. if Brennan owned iOS Coffee, it would be Brennan's access token, and if Phil owned iOS Beer, it would be Phil's access token.

**Comment by rodericj** [comment]
I think you can do this task separate from the repo. A chron that reads the event api and does the thing works

**Comment by jamescmartinez** [comment]
Very true. I can expose the events API instead of the iCal for anyone who wants it. Just let me know.

**Comment by jamescmartinez** [comment]
I'm going to close this. If someone is interested in doing this, ping me and I'll surface an API.
