### ISSUE TITLE
Smart App Banners

### ISSUE THREAD

**Issue by rodericj** [jamescmartinez/coffee#165]
Add smart app banners to the top of each view. We may need to add a row in the schema which is the app's App Store ID. 

https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html

**Comment by jamescmartinez** [comment]
Completed in https://github.com/jamescmartinez/coffee/commit/5b51ef1814602eb21032d6f9f32775620db4fb48
