### ISSUE TITLE
Groups should have owners

### ISSUE THREAD

**Issue by jamescmartinez** [jamescmartinez/coffee#222]
Currently, people who are given access to create events have full access to delete/edit everything for every group. This is dangerous and, though it's worked well for a small group, we've continued growing and this is no longer the best option.

**Comment by jamescmartinez** [comment]
Closing this. For now, I'm using the existing memberships model and restricting access in the admin panel based off group membership. 

These three commits:

f2abba68609855f4f4509afcfde642afe3197c5d
048f7cd7a83e63b93e3c624030bc6283d0596ad4
c33d4a1d52e9918eb015adb021f4038a88f7ea92

**Comment by rodericj** [comment]
A good fix
