### ISSUE TITLE
Hide inactive groups?

### ISSUE THREAD

**Issue by jamescmartinez** [jamescmartinez/coffee#272]
We have a few inactive groups. How should we prevent them from showing up on the home page?

Thinking only showing groups with an event in the last X days. Thoughts?

**Comment by rodericj** [comment]
I think that’s reasonable. This would require a change in the iOS app. It should just delete them from the local cache if they aren’t in the payload.

**Comment by rodericj** [comment]
On the iOS side we may want to consider URL based subscription.

**Comment by jamescmartinez** [comment]
> On the iOS side we may want to consider URL based subscription.

What do you mean?

**Comment by jamescmartinez** [comment]
Closing since the serverside work is completed for this.

**Comment by rodericj** [comment]
Nice. Looks good on mobile!
